
server:
  port: 80
logging:
  level:
    com.phd.mapper: debug
  #path: "D:/test/test.log"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: kaoqing
    password: kaoqing
    driver-class-name: org.postgresql.Driver
  mvc:
    servlet:
      load-on-startup: 1

mybatis:
  type-handlers-package: zsh.demos.postgres.mybatis.typehandler
  mapper-locations: classpath:mapping/*.xml

